// <auto-generated />
using Loushop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Loushop.Migrations
{
    [DbContext(typeof(LouShopContext))]
    [Migration("20241213120050_seedDataCategorymig")]
    partial class seedDataCategorymig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Loushop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "گروه لباس ورزشی",
                            Name = "لباس ورزشی"
                        },
                        new
                        {
                            Id = 2,
                            Description = "گروه ساعت مچی",
                            Name = "ساعت مچی"
                        },
                        new
                        {
                            Id = 3,
                            Description = "گروه کالای دیجیتال",
                            Name = "کالای دیجیتال"
                        },
                        new
                        {
                            Id = 4,
                            Description = "گروه لوازم منزل",
                            Name = "لوازم منزل"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
